export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const CHANGE_TAB = 'CHANGE_TAB';
export const SIGNOUT = 'SIGNOUT';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const REGISTERED_USERS_REQUEST = 'REGISTERED_USERS_REQUEST';
